[project]
name = "rss-downloader"
version = "0.1.0"
description = "A Simple RSS Download Manager"
readme = "README.md"
authors = [
    {name = "GrassSand", email = "grasssand@users.noreply.github.com"},
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "feedparser>=6.0.11",
    "loguru>=0.7.3",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
    "qbittorrent-api>=2025.7.0",
    "requests>=2.32.5",
]

[project.scripts]
rss-downloader = "rss_downloader:main"

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
